# _config.yml

title: "DevOps Upskill Challenge"
description: "DevOps Upskill Challenge: From 'Hello World' to Kubernetes"
baseurl: ""
url: "https://devopsupskillchallenge.com/"

markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme

include:
  - "*.md"
