# _config.yml

title: "DevOps Upskill Challenge"
description: "DevOps Upskill Challenge: From 'Hello World' to Kubernetes"
baseurl: ""
url: "https://devopsupskillchallenge.com/"

markdown: kramdown
theme: minimal

include:
  - "*.md"
